account/urls.py
from django.conf.urls import url

from .views import dashboard, logout_view, register_view, login_view

urlpatterns = [
        url(r'^dashboard/', dashboard, name="index"),
        url(r'^login/', login_view, name="login"),
        url(r'^register/', register_view, name="register"),
        url(r'^logout/', logout_view, name="logout"),
]

blogs/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    post_create,
    post_detail,
    post_list,
    post_delete,
)

urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^(?P<id>\d+)/$', post_detail, name="detail"),
]

event/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import event, event_detail
# from .views import

urlpatterns = [
    url(r'^$', event, name="home"),
    url(r'^(?P<id>\d+)/detail/$', event_detail, name="detail"),
]

gallery/urls.py
from django.conf.urls import url

from .views import pics, vids, auds

urlpatterns = [
        url(r'^pictures/', pics, name="pictures"),
        url(r'^$', pics, name="home"),
        url(r'^videos/$', vids, name="videos"),
        url(r'^audio/$', auds, name="audio"),
]

recon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from blogs.views import post_update, admin_post, post_delete, post_create
from base.views import index, about
from account.views import post, message
from event.views import  event_update ,admin_events , event_delete, event_create
from gallery.views import media_update, admin_media ,media_delete, media_create

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blogs/', include("blogs.urls", namespace="blog")),
    url(r'^gallery/', include("gallery.urls", namespace="gallery")),
    url(r'^events/', include("event.urls", namespace="events")),
    url(r'^$', index, name="home" ),
    url(r'^about/$', about, name="about"),
    url(r'^post/$', post, name="post" ),
    url(r'^message/$', message, name="message" ),

    url(r'^super/', include("account.urls", namespace="super")),
# post urls
    url(r'^super/blog/delete/(?P<id>\d+)/$', post_delete, name="blog-delete"),
    url(r'^super/blog/create', post_create, name="blog-create"),
    url(r'^super/blog/edit/(?P<id>\d+)/$', post_update,  name="blog-form"),
    url(r'^super/blog', admin_post, name="admin-blog"),
 # events urls
    url(r'^super/events/delete/(?P<id>\d+)/$', event_delete, name="event-delete"),
    url(r'^super/events/create', event_create, name="event-create"),
    url(r'^super/events/edit/(?P<id>\d+)/$', event_update,  name="event-form"),
    url(r'^super/events', admin_events, name="admin-event"),
# gallery urls
    url(r'^super/media/delete/(?P<id>\d+)/$', media_delete, name="media-delete"),
    url(r'^super/media/create', media_create, name="media-create"),
    url(r'^super/media/edit/(?P<id>\d+)/$', media_update,  name="media-form"),
    url(r'^super/media', admin_media, name="admin-media")
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models

# Create your models here.

event/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Event(models.Model):
    title = models.CharField(max_length=100)
    organizer = models.CharField(max_length=100, null=True, blank=True,)
    venue = models.CharField(max_length=100)
    theme = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=False, auto_now=False)
    cover = models.FileField()
    map_image = models.FileField()
    map_url = models.URLField(null=True, blank=True,)

    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("events:detail", kwargs={"id": self.id})

    def get_edit_url(self):
        return reverse("event-form", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("event-delete", kwargs={"id": self.id})

event/forms.py
from django import forms

from .models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            "title",
            "organizer",
            "venue",
            "theme",
            "date",
            "cover",
            "map_image",
            "map_url"
        ]

base/views.py
from django.shortcuts import render
from django.contrib.auth import (
    authenticate,
    login,
)


def index(request):
    if not request.user.is_authenticated():
        user = authenticate(username='alby', password='qazwsxedc')
        login(request, user)
        print(request.user)
    return render(request, 'index.html', {})


def about(request):
    print(request.user)
    return render(request, 'about.html', {})

event/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .forms import EventForm
from .models import Event
from account.models import UserProfile
from account.utils import create_action

def event(request):
    event = Event.objects.all()
    return render (request, 'events.html', {'events': event })


def event_detail(request , id=None):
    instance = get_object_or_404(Event, id=id)
    context = {
    "instance": instance
    }
    return render (request, 'event-detail.html', context )

@login_required
def event_create(request):
    profile = get_object_or_404(UserProfile, user=request.user)
    instance = ""
    if profile.title == "editor":
        form = EventForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            create_action(request.user, 'added  the event', instance)
            created = instance
            print(created)
            if created:
                messages.success(request, "The event \""+str(instance.title)+"\" is created successfully")
            else:
                messages.info(request, "Oops an error occured")
            return HttpResponseRedirect(reverse("admin-event"))
        context = {
             "form": form,
             "instance": instance
        }
    else:
        return redirect(reverse("home"))
    return render (request, 'super/event-form.html', {})

@login_required
def event_update(request, id=None):
    instance = get_object_or_404(Event, id=id)
    profile = get_object_or_404(UserProfile, user=request.user)
    if profile.title == "editor":
        form = EventForm(request.POST or None, request.FILES or None, instance=instance)
        print (form)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            create_action(request.user, 'Updated the the event', instance)
            created = instance
            print(created)
            if created:
                messages.success(request, "The event \""+str(instance.title)+"\" is succefully updated")
            else:
                messages.info(request, "Oops an error occured")
            return HttpResponseRedirect(reverse("admin-event"))
        context = {
             "form": form,
             "instance": instance
        }
    else:
        return redirect(reverse("home"))
    return render (request, 'super/event-form.html', context)


@login_required
def event_delete(request, id):
    profile = get_object_or_404(UserProfile, user=request.user)
    if profile.title == "editor":
        instance = get_object_or_404(Event, id=id)
        instance.delete()
    else:
        return redirect(reverse("home"))
    return redirect(reverse("admin-event"))

@login_required
def admin_events(request):
    profile = get_object_or_404(UserProfile, user=request.user)
    if profile.title == "editor":
        event = Event.objects.all()
    else:
        return redirect(reverse("home"))
    return render (request, 'super/admin-event.html', {'events': event })

templates/super/admin-event.html
{% extends "super/base.html" %}
{% load static  %}
{% block extra-css %}
  <link rel="" href="{% static '/css/zabuto_calendar.css' %}">
{% endblock %}
{% block se %} class="active" {% endblock %}
{% block content %}
 <!-- main  -->
 <div class="row">
   <div class="col s12 m12 l10 offset-l1" style="text-align: center; margin-bottom: 10px">
     {% for message in messages %}
       <div class="" style="
       background-color: rgba(0, 0, 0, 0.5);
       color: white;
       padding: 10px;
       display: inline-block">
         {{message}}
       </div>
     {% endfor %}
   </div>
 </div>
 <div class="row">
   <div class="col s12 m12 l10 offset-l1 z-depth-2 al-post">
     <div class="al-post-head" style="display: flex">
       <p>Events </p>
       <p>Total: </p>
       <p ><a href="{% url 'blog-create' %}" class="recon-btn"><div class="th-icon">Add</div></a></p>
     </div>
     <div class="al-events gal">
         <table>
             <tr>
                 <th>Title</th>
                 <th>Organizer</th>
                 <th>Time Left</th>
                 <th>...</th>
             </tr>
           {% for obj in events %}
             <tr>
                 <td>{{ obj.title }}</td>
                 <td>{{ obj.organizer }}</td>
                 <td>{{ obj.date|timeuntil }}</td>
                 <td><a href="{{ obj.get_edit_url }}"><span class="fa fa-pencil"></span> </a></td>
                 <td><a href="#post{{obj.id}}"><span class="fa fa-trash"></span></a></td>
             </tr>
           {% endfor %}
         </table>
         {% for obj in events %}
         <div id="post{{obj.id}}" class="modal">
           <div class="modal-content">
             <h4>Are you sure you want to delete this post</h4>
             <p>Note: Deleted post are not recoverable</p>
           </div>
           <div class="modal-footer">
             <a href="#!" class=" modal-action modal-close waves-effect waves-grey btn-flat">Cancel</a>
             <a href="{{ obj.get_delete_url }}" class=" modal-action modal-close waves-effect waves-red btn-flat">Delete</a>
           </div>
         </div>
        {% endfor %}
     </div>
   </div>
 </div>

  {% endblock %}
  {% block extra-js %}
  <script type="text/javascript" src="{% static 'js/zabuto_calendar.js' %}"></script>
  {% endblock %}

templates/super/admin-post.html
{% extends "super/base.html" %}
{% load static  %}
{% block sp %} class="active" {% endblock %}
{% block content %}
 <!-- main  -->
 </div>
 <div class="row">
   <div class="col s12 m12 l10 offset-l1" style="text-align: center; margin-bottom: 10px">
     {% for message in messages %}
       <div class="" style="
       background-color: rgba(0, 0, 0, 0.5);
       color: white;
       padding: 10px;
       display: inline-block">
         {{message}}
       </div>
     {% endfor %}
   </div>
 </div>
<div class="row">
  <div class="col s12 m12 l10 offset-l1 z-depth-2 al-post">
    <div class="al-post-head" style="display: flex">
      <p>All audio files </p>
      <p>Total: </p>
      <p ><a href="{% url 'blog-create' %}" class="recon-btn"><div class="th-icon">Add</div></a></p>
    </div>
    <div class="al-events gal">
        <table>
            <tr>
                <th>Title</th>
                <th>State</th>
                <th>Author</th>
                <th>...</th>
            </tr>
          {% for obj in qs %}
            <tr>
                <td>{{ obj.title }}</td>
                <td>{% if obj.draft %} Draft {% else %} Published {% endif %}</td>
                <td>{% if obj.user == request.user %}You{% else %}{{ obj.user.username}}{% endif %}</td>
                <td><a href="{{ obj.get_edit_url }}"><span class="fa fa-pencil"></span> </a></td>
                <td><a href="#post{{obj.id}}"><span class="fa fa-trash"></span></a></td>
            </tr>
          {% endfor %}
        </table>
    </div>
    {% for obj in qs %}
    <div id="post{{obj.id}}" class="modal">
      <div class="modal-content">
        <h4>Are you sure you want to delete this post</h4>
        <p>Note: Deleted post are not recoverable</p>
      </div>
      <div class="modal-footer">
        <a href="#!" class=" modal-action modal-close waves-effect waves-grey btn-flat">Cancel</a>
        <a href="{{ obj.get_delete_url }}" class=" modal-action modal-close waves-effect waves-red btn-flat">Delete</a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
  {% endblock %}

templates/super/all-event.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <meta name="description" content="Reconcilers International">
    <title>Reconcilers International</title>
    <link rel="stylesheet" href="../css/materialize.min.css">
    <link rel="stylesheet" href="../fonts/font-awesome-4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="../css/main.css">
</head>
<body>
    <!-- Navbar section -->
  <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo logo"><img src="../images/nav1.png" alt=""><span>Reconcilers International</span></a>
          <a href="#" data-activates="mobile-view" class="button-collapse">
            <i class="hamburger"></i>
            <i class="hamburger one"></i>
            <i class="hamburger two"></i></a>
          <ul class="right hide-on-med-and-down">
            <li><a href="../index.html">Home</a><div></div></li>
            <li><a href="../about.html">About-Us</a><div></div></li>
            <li><a href="../events.html">Events</a><div></div></li>
            <li><a href="../blogs.html">Blogs</a><div></div></li>
            <li><a href="../gallery.html">Gallery</a><div></div></li>
            <li class="cus-btn"><a href="payment.php">Donate</a></li>
          </ul>
          <ul class="side-nav" id="mobile-view">
            <li><a href="index.html">Home</a></li>
            <li><a href="about.html">About-Us</a></li>
            <li><a href="events.html">Events</a></li>
            <li><a href="blogs.html">Blogs</a></li>
            <li><a href="gallery.html">Gallery</a></li>
            <li class="cus-btn"><a href="payment.php">Donate</a></li>
          </ul>
        </div>
    </nav>
  </div>
  <!-- Navbar Section end -->
 <!-- Admin-Nav -->
 <div class="admin-info">
    <nav>
      <ul class="ad-info">
        <li class="admin-img">
          <img src="../images/passport.png" alt="">
        </li>
        <li class="admin-name"><span>Eric Kojo Abbey</span></li>
      </ul>
    </nav>
 </div>
 <div class="admin-nav">
  <nav>
    <a href="#!" class="dashboard"><span><i class="fa fa-dashboard"></i></span><span>Admin Panel</span></a>
    <ul>
      <li><a href="index.html"><span class="icon"><i class="fa fa-home"></i></span><span class="icon-text">Home</span></a></li>
      <li class=""><a href="admin-post.html"><span class="icon"><i class="fa fa-newspaper-o"></i></span><span class="icon-text">Manage Post</span></a></li>
      <li class="active"><a href="admin-event.html"><span class="icon"><i class="fa fa-calendar"></i></span><span class="icon-text">Manage Events</span></a></li>
      <li><a href="#"><span class="icon"><i class="fa fa-camera"></i></span><span class="icon-text">Add Media</span></a></li>
       <li><a href="#"><span class="icon"><i class="fa fa-power-off"></i></span><span class="icon-text">Logout</span></a></li>
    </ul>
  </nav>
 </div>
 <!-- End Admin-Nav -->
 <!-- main  -->
 </div>
<div class="row">
  <div class="col s12 m12 l10 offset-l1 z-depth-2 al-post">
    <div class="row breadcrumbs">
      <div class="col s12 m12 l12"><p>Manage Event // All Post</p></div>
    </div>
    <div class="al-post-head">
      <p>All Events Upcoming</p>
    </div>
    <div class="al-events">
        <table>
            <tr>
                <th>Name</th>
                <th>In</th>
                <th>By</th>
                <th>...</th>
            </tr>
            <tr>
                <td>Palm Sunday</td>
                <td>30 days</td>
                <td>Reconcilers Int</td>
                <td><a href="event-form.html"><span class="fa fa-pencil"></span> </a><a href=""><span class="fa fa-trash"></span></a></td>
            </tr>
            <tr>
                <td>May Day</td>
                <td>2 months</td>
                <td>National</td>
                <td><a href=""><span class="fa fa-pencil"></span> </a><a href=""><span class="fa fa-trash"></span></a></td>
            </tr>
            <tr>
                <td>Palm Sunday</td>
                <td>30 days</td>
                <td>Reconcilers Int</td>
                <td><a href=""><span class="fa fa-pencil"></span> </a><a href=""><span class="fa fa-trash"></span></a></td>
            </tr>
            <tr>
                <td>Palm Sunday</td>
                <td>30 days</td>
                <td>Reconcilers Int</td>
                <td><a href=""><span class="fa fa-pencil"></span> </a><a href=""><span class="fa fa-trash"></span></a></td>
            </tr>
            <tr>
                <td>Palm Sunday</td>
                <td>30 days</td>
                <td>Reconcilers Int</td>
                <td><a href="event-form.html"><span class="fa fa-pencil"></span> </a><a href=""><span class="fa fa-trash"></span></a></td>
            </tr>
        </table>
    </div>
  </div>
</div>
  </div> 
 <!-- end main -->
    <script type="text/javascript" src="../js/jquery-1.11.2.min.js"></script>
    <script type="text/javascript" src="../js/materialize.min.js"></script>
    <script type="text/javascript" src="../js/jquery.nicescroll.min.js"></script>      
    <script type="text/javascript" src="../js/functions.js"></script>             

</body>
</html>

templates/super/all-media.html
{% extends "super/base.html" %}
{% block content%}
<div class="row">
  <div class="col s12 m12 l10 offset-l1" style="text-align: center; margin-bottom: 10px">
    {% for message in messages %}
      <div class="" style="
      background-color: rgba(0, 0, 0, 0.5);
      color: white;
      padding: 10px;
      display: inline-block">
        {{message}}
      </div>
    {% endfor %}
  </div>
</div>
<div class="row">
  <div class="col s12 m12 l10 offset-l1 z-depth-2 al-post">
    <div class="al-post-head" style="display: flex">
      <p>All media files </p>
      <p>Total: {{ media.count }}</p>
      <p ><a href="{% url 'media-create' %}" class="recon-btn"><div class="th-icon">Add</div></a></p>
    </div>
    <div class="al-events gal">
        <table>
            <tr>
                <th>Title</th>
                <th>Artist</th>
                <th>Type</th>
                <th>Source</th>
                <th>...</th>
            </tr>
            {% for obj in media  %}
            <tr>
                <td>{{ obj.title }}</td>
                <td>{{ obj.artist }}</td>
                <td>{{ obj.type }}</td>
                <td>{{ obj.source }}</td>
                <td><a href="{{ obj.get_edit_url }}"><span class="fa fa-pencil"></span> </a></td>
                <td><a href="#post{{obj.id}}"><span class="fa fa-trash"></span></a></td>
            </tr>
            {% endfor %}
        </table>
        {% for obj in media %}
        <div id="post{{obj.id}}" class="modal">
          <div class="modal-content">
            <h4>Are you sure you want to delete this post</h4>
            <p>Note: Deleted post are not recoverable</p>
          </div>
          <div class="modal-footer">
            <a href="#!" class=" modal-action modal-close waves-effect waves-grey btn-flat">Cancel</a>
            <a href="{{ obj.get_delete_url }}" class=" modal-action modal-close waves-effect waves-red btn-flat">Delete</a>
          </div>
        </div>
          {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

templates/super/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <meta name="description" content="Reconcilers International">
    <title>Reconcilers International</title>
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static '/fonts/font-awesome-4.4.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    {% block extra-css %}
    {% endblock %}
</head>
<body>
    <!-- Navbar section -->
    <div class="navbar-fixed">
        <nav>
          <div class="nav-wrapper">
            <a href="#!" class="brand-logo logo"><img src="{% static 'images/nav1.png' %}" alt=""><span>Reconcilers International</span></a>
            <a href="#" data-activates="mobile-view" class="button-collapse">
              <i class="hamburger"></i>
              <i class="hamburger one"></i>
              <i class="hamburger two"></i></a>
            <ul class="right hide-on-med-and-down">
              <li><a href="{% url 'home' %}">Home</a><div></div></li>
              <li><a href="{% url 'about' %}">About-Us</a><div></div></li>
              <li><a href="{% url 'events:home'%}">Events</a><div></div></li>
              <li><a href="{% url 'blog:list'%}">Blogs</a><div></div></li>
              <li><a href="{% url 'gallery:pictures'%}">Gallery</a><div></div></li>
              <li class="cus-btn"><a href="payment.php">Donate</a></li>
            </ul>
            <ul class="side-nav" id="mobile-view">
              <li><a href="{% url 'home' %}">Home</a></li>
              <li><a href="{% url 'about' %}">About-Us</a></li>
              <li><a href="{% url 'events:home'%}">Events</a></li>
              <li><a href="{% url 'blog:list'%}">Blogs</a></li>
              <li><a href="{% url 'gallery:pictures'%}">Gallery</a></li>
              <li class="cus-btn"><a href="payment.php">Donate</a></li>
            </ul>
          </div>
      </nav>
    </div>
  <!-- Navbar Section end -->
 <!-- Admin-Nav -->
 <div class="admin-info">
    <nav>
      <ul class="ad-info">
        <li class="admin-img">
          <img src="{% static '/images/passport.png' %}" alt="">
        </li>
        <li class="admin-name"><span>{{request.user.username|capfirst}}</span></li>
      </ul>
    </nav>
 </div>
 <div class="admin-nav">
  <nav>
    <a href="#!" class="dashboard"><span><i class="fa fa-dashboard"></i></span><span>Admin Panel</span></a>
    <ul>
      <li {% block si %}{% endblock %}><a href="{% url 'super:index'%}"><span class="icon"><i class="fa fa-home"></i></span><span class="icon-text">Home</span></a></li>
      <li {% block sp %}{% endblock %}><a href="{% url 'admin-blog' %}"><span class="icon"><i class="fa fa-newspaper-o"></i></span><span class="icon-text">Manage Post</span></a></li>
      <li {% block se %}{% endblock %}><a href="{% url 'admin-event' %}"><span class="icon"><i class="fa fa-calendar"></i></span><span class="icon-text">Manage Events</span></a></li>
      <li {% block sm %}{% endblock %}><a href="{% url 'admin-media' %}"><span class="icon"><i class="fa fa-camera"></i></span><span class="icon-text">Add Media</span></a></li>
      <li><a href="{% url 'super:logout' %}"><span class="icon"><i class="fa fa-power-off"></i></span><span class="icon-text">Logout</span></a></li>
    </ul>
  </nav>
 </div>
 <!-- End Admin-Nav -->
 {% block content %}

 {% endblock %}
</div>
<!-- end main -->
  <script type="text/javascript" src="{% static '/js/jquery-1.11.2.min.js' %}"></script>
  <script type="text/javascript" src="{% static '/js/materialize.min.js' %}"></script>
  <script type="text/javascript" src="{% static '/js/jquery.nicescroll.min.js' %}"></script>
  <script type="text/javascript" src="{% static '/js/functions.js' %}"></script>
  {% block extra-js %}
  {% endblock %}
</body>
</html>

templates/super/event-form.html
{% extends "super/base.html" %}
{% load static  %}
{% block se %} class="active" {% endblock %}
{% block content %}
 <!-- main  -->
 <div class="row">
  <div class="col s12 m12 l10 offset-l1 post-form z-depth-2">
    <div class="row breadcrumbs">
      <div class="col s12 m12 l12"><p><a href="{% url 'admin-event' %}">Manage Event</a> // Add</p></div>
    </div>
    <div class="about-info">
        <h2>Event Add or Update</h2>
    </div>
    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row">
          <div class="input-field col s12 m12 l8 offset-l2">
            <input id="title" type="text" class="validate" name="title" value="{{instance.title}}">
            <label for="title">Event Title</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12 m12 l8 offset-l2">
            <input id="organizer" type="text" class="validate" name="organizer" value="{{ instance.organizer}}">
            <label for="organizer">Event Organiser</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12 m12 l8 offset-l2">
            <input id="venue" type="text" class="validate" name="venue" value="{{ instance.venue}}">
            <label for="venue">Event Venue</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12 m12 l8 offset-l2">
            <input id="theme" type="text" class="validate" name="theme" value="{{ instance.theme}}">
            <label for="theme">Event Theme</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12 m7 l8 offset-l2">
            <input id="datetime" type="text" name="date" value="{{ instance.date|date:'Y-m-d H:i'}}" placeholder="{% now 'Y-m-d H:i' %}" class="validate">
            <label for="datetime">Event Date &amp; time</label>
          </div>
        </div>
        <div class="row">
          <div class="col s12 m12 l8 offset-l2 file-field input-field">
            <div class="btn">
              <span>Cover Image</span>
              <input type="file" name="cover" value="{{ instance.cover.url }}">
            </div>
            <div class="file-path-wrapper">
              <input class="file-path validate" type="text" placeholder="Choose an Image" name="cover" value="{{ instance.cover.name }}">
            </div>
          </div>
        </div>
         <div class="row">
          <div class="col s12 m12 l8 offset-l2 file-field input-field">
            <div class="btn">
              <span>Map Image</span>
              <input type="file"  name="map_image" value="{{ instance.map_image.url }}">
            </div>
            <div class="file-path-wrapper">
              <input class="file-path validate" type="text" placeholder="Choose an Image"  name="map_image" value="{{ instance.map_image.name }}">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12 m12 l8 offset-l2">
            <input id="map_url" type="url" name="map_url" value="{{ instance.map_url }}" class="validate">
            <label for="map_url">Map Url</label>
          </div>
        </div>
        <div class="row send">
          <div class="col s6 m6 l3 offset-l2 post-save">
            <input type="submit" value="Save">
          </div>
        </div>
    </form>
  </div>
{% endblock %}
{% block extra-js %}
  <script type="text/javascript" src="{% static 'js/jquery.formatter.min.js' %}"></script>
{% endblock %}

templates/super/media-form.html
{% extends "super/base.html" %}
{% load static  %}
{% block sm %} class="active" {% endblock %}
{% block content %}
 <div class="row">
  <div class="col s12 m12 l10 offset-l1 post-form z-depth-2">
    <div class="row breadcrumbs">
      <div class="col s12 m12 l12"><p><a href="{% url 'admin-media' %}">Manage Event </a>// Add</p></div>
    </div>
    <div class="about-info">
        <h2>Add or Update Media</h2>
    </div>
    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row">
          <div class="input-field col s12 m12 l8 offset-l2">
            <input id="title" type="text" class="validate" name="title" value="{{instance.title}}">
            <label for="title">Media Title</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12 m12 l8 offset-l2">
            <input id="title" type="text" class="validate" name="artist" value="{{instance.artist }}">
            <label for="title">Artist</label>
          </div>
        </div>
        <div class="row">
          <div class="col s12 m12 l8 offset-l2 file-field input-field">
            <div class="btn">
              <span>Media source</span>
              <input type="file" name="source" value="{{instance.source.url }}">
            </div>
            <div class="file-path-wrapper">
              <input class="file-path validate" type="text" placeholder="Choose an Image" value="{{instance.source.name }}">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12 m12 l8 offset-l2">
            <input id="title" type="text" class="validate" name="url" value="{{instance.url }}" disabled="disabled" style="cursor: not-allowed;">
            <label for="title">Url</label>
          </div>
        </div>
        <div class="row send">
          <div class="col s6 m6 l3 offset-l2 post-save">
            <input type="submit" value="Save">
          </div>
        </div>
    </form>
  </div>
{% endblock %}