blogs/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    post_create,
    post_detail,
    post_list,
    post_delete,
)

urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^(?P<id>\d+)/$', post_detail, name="detail"),
]

event/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import event, event_detail
# from .views import

urlpatterns = [
    url(r'^$', event, name="home"),
    url(r'^(?P<id>\d+)/detail/$', event_detail, name="detail"),
]

gallery/urls.py
from django.conf.urls import url

from .views import pics, vids, auds

urlpatterns = [
        url(r'^pictures/', pics, name="pictures"),
        url(r'^$', pics, name="home"),
        url(r'^videos/$', vids, name="videos"),
        url(r'^audio/$', auds, name="audio"),
]

recon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from blogs.views import post_update, admin_post, post_delete, post_create
from base.views import index, about
from account.views import post, message
from event.views import  event_update ,admin_events , event_delete, event_create
from gallery.views import media_update, admin_media ,media_delete, media_create

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blogs/', include("blogs.urls", namespace="blog")),
    url(r'^gallery/', include("gallery.urls", namespace="gallery")),
    url(r'^events/', include("event.urls", namespace="events")),
    url(r'^$', index, name="home" ),
    url(r'^about/$', about, name="about"),
    url(r'^post/$', post, name="post" ),
    url(r'^message/$', message, name="message" ),

    url(r'^super/', include("account.urls", namespace="super")),
# post urls
    url(r'^super/blog/delete/(?P<id>\d+)/$', post_delete, name="blog-delete"),
    url(r'^super/blog/create', post_create, name="blog-create"),
    url(r'^super/blog/edit/(?P<id>\d+)/$', post_update,  name="blog-form"),
    url(r'^super/blog', admin_post, name="admin-blog"),
 # events urls
    url(r'^super/events/delete/(?P<id>\d+)/$', event_delete, name="event-delete"),
    url(r'^super/events/create', event_create, name="event-create"),
    url(r'^super/events/edit/(?P<id>\d+)/$', event_update,  name="event-form"),
    url(r'^super/events', admin_events, name="admin-event"),
# gallery urls
    url(r'^super/media/delete/(?P<id>\d+)/$', media_delete, name="media-delete"),
    url(r'^super/media/create', media_create, name="media-create"),
    url(r'^super/media/edit/(?P<id>\d+)/$', media_update,  name="media-form"),
    url(r'^super/media', admin_media, name="admin-media")
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models

# Create your models here.

blogs/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    image = models.FileField(null=True, blank=True,)
    content = models.TextField()
    # height = models.IntegerField(default=0)
    # width = models.IntegerField(default=0)
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    num_votes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"id": self.id})

    def get_edit_url(self):
        return reverse("blog-form", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("blog-delete", kwargs={"id": self.id})

    class Meta:
        ordering = ["-timestamp"]


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default='')
    blog = models.ForeignKey(Post, on_delete=models.CASCADE, default='', blank=True, null=True)
    content = models.TextField()
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-time',)

    def __str__(self):
        return self.blog.title

class like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default='')
    blog = models.ForeignKey(Post, on_delete=models.CASCADE, default='', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.blog.title

event/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Event(models.Model):
    title = models.CharField(max_length=100)
    organizer = models.CharField(max_length=100, null=True, blank=True,)
    venue = models.CharField(max_length=100)
    theme = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=False, auto_now=False)
    cover = models.FileField()
    map_image = models.FileField()
    map_url = models.URLField(null=True, blank=True,)

    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("events:detail", kwargs={"id": self.id})

    def get_edit_url(self):
        return reverse("event-form", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("event-delete", kwargs={"id": self.id})

gallery/models.py
from django.core.urlresolvers import reverse
from django.db import models

class Media(models.Model):
    title = models.CharField(max_length=100)
    artist = models.CharField(max_length=100, blank=True, null=True)
    source = models.FileField(blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    type = models.CharField(max_length=10, blank=True, null=True)

    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    class Meta:
        ordering = ['-timestamp', '-updated']

    def __str__(self):
        return self.title

    def get_edit_url(self):
        return reverse("media-form", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("media-delete", kwargs={"id": self.id})

blogs/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "publish"
        ]


class CommentForm(forms.Form):
    blog = forms.CharField(widget=forms.HiddenInput)
    content = forms.CharField(widget=forms.Textarea, label="")

event/forms.py
from django import forms

from .models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            "title",
            "organizer",
            "venue",
            "theme",
            "date",
            "cover",
            "map_image",
            "map_url"
        ]

gallery/forms.py
from django import forms

from .models import Media

class MediaForm(forms.ModelForm):
    class Meta:
        model = Media
        fields = [
            "title",
            "artist",
            "source",
            "url",
        ]

base/views.py
from django.shortcuts import render
from django.contrib.auth import (
    authenticate,
    login,
)


def index(request):
    if not request.user.is_authenticated():
        user = authenticate(username='alby', password='qazwsxedc')
        login(request, user)
        print(request.user)
    return render(request, 'index.html', {})


def about(request):
    print(request.user)
    return render(request, 'about.html', {})

blogs/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import render, get_object_or_404,redirect

from account.utils import create_action
from account.models import UserProfile
from .forms import PostForm, CommentForm
from .models import Post, Comment, like

today = datetime.now().strftime("%Y-%m-%d")


@login_required(login_url='/login/')
def post_create(request):
    profile = get_object_or_404(UserProfile, user=request.user)
    print(profile.title)
    if profile.title == "editor":
        if not request.user.is_authenticated:
            raise Http404
        form = PostForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            if str(instance.publish) != today:
                instance.draft = True
            else:
                instance.draft = False
            instance.save()
            create_action(request.user, 'posted the message', instance)
            created = instance
            print(created)
            if created:
                if not instance.draft:
                    messages.success(request, "The blog \""+str(instance.title)+"\" is created succefully and we live")
                else:
                    messages.success(request, "The blog \""+str(instance.title)+"\" is save succefully")
            else:
                messages.info(request, "Oops an error occured")
            return HttpResponseRedirect(reverse("admin-blog"))
        context = {
             "form": form,
             "instance": ""
        }
    else:
        return redirect('home')
    return render(request, "super/post-form.html", context)


def post_detail(request, id):
    instance = get_object_or_404(Post, id=id)
    com_user = get_object_or_404(User, id=request.user.id),
    initial_data = {
        'blog': instance,
        'user':com_user
    }
    if request.is_ajax():
        blog_id = request.POST.get("blog-id")
        print(blog_id)
        vote = like.objects.filter(blog=instance, user=request.user)
        if vote.exists():
            vote.delete()
            count = instance.like_set.count()
            return JsonResponse({'count': str(count)} )
        else:
            new_like,created = like.objects.get_or_create(blog=instance, user=request.user)
            count = instance.like_set.count()
            create_action(request.user, 'likes', new_like)
            return JsonResponse({'count':   count})

    form = CommentForm(request.POST or None, initial=initial_data)
    current_user = request.user.id
    detail_url = request.path
    if form.is_valid():
        c_type = instance
        user = request.user
        content_data = form.cleaned_data.get('content')
        new_comment, created = Comment.objects.get_or_create(
            user=user,
            blog=c_type,
            content=content_data,
        )
        create_action(request.user, 'commented on your post', new_comment)
        return HttpResponseRedirect('/')

    context = {
        'instance': instance,
        'form': form,
        'current_user': current_user,
        'path': detail_url
    }
    return render(request, "blog_detail.html", context)


def post_list(request):
    queryset = Post.objects.exclude(draft=True)  # .order_by("-timestamp")
    # profile = UserProfile.objects.filter(user=request.user)
    query = request.GET.get("q")
    current_user = request.user.id
    if query:
        queryset = queryset.filter(Q(title__icontains=query) | Q(author__icontains=query)).distinct()
    obj_count = queryset.count()
    context = {
        "object_list": queryset,
        "title": "list",
        "current_user": current_user,
        # "pro": profile,
        'obj_count': obj_count
    }
    return render(request, "blogs.html", context)


@login_required(login_url='login')
def post_update(request, id=None):
    instance = get_object_or_404(Post, id=id)
    profile = get_object_or_404(UserProfile, user=request.user)
    today = datetime.now().strftime("%Y-%m-%d")
    if profile.title == "editor":
        form = PostForm(request.POST or None, request.FILES or None, instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            if str(instance.publish) <= today:
                instance.draft = False
            else:
                instance.draft = True
            instance.save()
            create_action(request.user, 'Updated the blog', instance)
            created = instance
            print(created)
            if created:
                messages.success(request, "The blog \""+str(instance.title)+"\" is succefully updated")
            else:
                messages.info(request, "Oops an error occured")
            return HttpResponseRedirect(reverse("admin-blog"))
        context = {
             "form": form,
             "instance": instance
        }
    else:
        return redirect('home')
    return render(request, "super/post-form.html", context)


@login_required(login_url='login')
def post_delete(request, id):
    profile = get_object_or_404(UserProfile, user=request.user)
    if profile.title == "editor":
        instance = get_object_or_404(Post, id=id)
        instance.delete()
    else:
        return redirect(reverse("home"))
    return redirect("posts:list")


@login_required(login_url='login')
def admin_post(request):
    profile = get_object_or_404(UserProfile, user=request.user)
    if profile.title == "editor":
        queryset = Post.objects.all().filter(user=request.user)
    else:
        return redirect(reverse("home"))
    context = {
        'qs': queryset
    }
    return render(request, 'super/admin-post.html', context)

event/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .forms import EventForm
from .models import Event
from account.models import UserProfile
from account.utils import create_action

def event(request):
    event = Event.objects.all()
    return render (request, 'events.html', {'events': event })


def event_detail(request , id=None):
    instance = get_object_or_404(Event, id=id)
    context = {
    "instance": instance
    }
    return render (request, 'event-detail.html', context )

@login_required
def event_create(request):
    profile = get_object_or_404(UserProfile, user=request.user)
    instance = ""
    if profile.title == "editor":
        form = EventForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            create_action(request.user, 'added  the event', instance)
            created = instance
            print(created)
            if created:
                messages.success(request, "The event \""+str(instance.title)+"\" is created successfully")
            else:
                messages.info(request, "Oops an error occured")
            return HttpResponseRedirect(reverse("admin-event"))
        context = {
             "form": form,
             "instance": instance
        }
    else:
        return redirect(reverse("home"))
    return render (request, 'super/event-form.html', {})

@login_required
def event_update(request, id=None):
    instance = get_object_or_404(Event, id=id)
    profile = get_object_or_404(UserProfile, user=request.user)
    if profile.title == "editor":
        form = EventForm(request.POST or None, request.FILES or None, instance=instance)
        print (form)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            create_action(request.user, 'Updated the the event', instance)
            created = instance
            print(created)
            if created:
                messages.success(request, "The event \""+str(instance.title)+"\" is succefully updated")
            else:
                messages.info(request, "Oops an error occured")
            return HttpResponseRedirect(reverse("admin-event"))
        context = {
             "form": form,
             "instance": instance
        }
    else:
        return redirect(reverse("home"))
    return render (request, 'super/event-form.html', context)


@login_required
def event_delete(request, id):
    profile = get_object_or_404(UserProfile, user=request.user)
    if profile.title == "editor":
        instance = get_object_or_404(Event, id=id)
        instance.delete()
    else:
        return redirect(reverse("home"))
    return redirect(reverse("admin-event"))

@login_required
def admin_events(request):
    profile = get_object_or_404(UserProfile, user=request.user)
    if profile.title == "editor":
        event = Event.objects.all()
    else:
        return redirect(reverse("home"))
    return render (request, 'super/admin-event.html', {'events': event })

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <meta name="description" content="Reconcilers International">
    <title>Reconcilers International</title>
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    {% block inner_css %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block extra_css %}
    {% endblock %}
</head>
<body>
    <!-- Navbar section -->

  <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo logo"><img src="{% static 'images/nav1.png' %}" alt=""><span>Reconcilers International</span></a>
          <a href="#" data-activates="mobile-view" class="button-collapse">
            <i class="hamburger"></i>
            <i class="hamburger one"></i>
            <i class="hamburger two"></i></a>
          <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'home' %}">Home</a><div></div></li>
            <li><a href="{% url 'about' %}">About-Us</a><div></div></li>
            <li><a href="{% url 'events:home'%}">Events</a><div></div></li>
            <li><a href="{% url 'blog:list'%}">Blogs</a><div></div></li>
            <li><a href="{% url 'gallery:pictures'%}">Gallery</a><div></div></li>
            <li class="cus-btn"><a href="payment.php">Donate</a></li>
          </ul>
          <ul class="side-nav" id="mobile-view">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About-Us</a></li>
            <li><a href="{% url 'events:home'%}">Events</a></li>
            <li><a href="{% url 'blog:list'%}">Blogs</a></li>
            <li><a href="{% url 'gallery:pictures'%}">Gallery</a></li>
            <li class="cus-btn"><a href="payment.php">Donate</a></li>
          </ul>
        </div>
    </nav>
  </div>
  <!-- Navbar Section end -->
  {% block content %}
  {% endblock %}
  <script type="text/javascript" src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
  {% block extra-js %}
  {% endblock %}
  <div class="container">
    <div class="row footer">
      <div class="col s12 m3 l3 foot">
      <h5 class="text-purple">Know More </h5>
        <ul>
          <li><a href="#">About-Us</a></li>
          <li><a href="#">Events</a></li>
          <li><a href="#">Projects</a></li>
          <li><a href="#">Gallery</a></li>
          <li><a href="#">Blog</a></li>
        </ul>
      </div>
      <div class="col s12 m3 l3 foot">
      <h5 class="text-blue">Join-Us</h5>
        <div class="fb icon">
            <a href="">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="30" height="30">
              <path d="M9.5 3h2.5v-3h-2.5c-1.93 0-3.5 1.57-3.5 3.5v1.5h-2v3h2v8h3v-8h2.5l0.5-3h-3v-1.5c0-0.271 0.229-0.5 0.5-0.5z"></path>
            </svg><span> &nbsp; 1000+</span>
            </a>
        </div>
        <div class="tw icon">
            <a href="">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="30" height="30">
                <path  d="M16 3.538c-0.588 0.263-1.222 0.438-1.884 0.516 0.678-0.406 1.197-1.050 1.444-1.816-0.634 0.375-1.338 0.65-2.084 0.797-0.6-0.638-1.453-1.034-2.397-1.034-1.813 0-3.281 1.469-3.281 3.281 0 0.256 0.028 0.506 0.084 0.747-2.728-0.138-5.147-1.444-6.766-3.431-0.281 0.484-0.444 1.050-0.444 1.65 0 1.138 0.578 2.144 1.459 2.731-0.538-0.016-1.044-0.166-1.488-0.409 0 0.013 0 0.028 0 0.041 0 1.591 1.131 2.919 2.634 3.219-0.275 0.075-0.566 0.116-0.866 0.116-0.212 0-0.416-0.022-0.619-0.059 0.419 1.303 1.631 2.253 3.066 2.281-1.125 0.881-2.538 1.406-4.078 1.406-0.266 0-0.525-0.016-0.784-0.047 1.456 0.934 3.181 1.475 5.034 1.475 6.037 0 9.341-5.003 9.341-9.341 0-0.144-0.003-0.284-0.009-0.425 0.641-0.459 1.197-1.038 1.637-1.697z"></path>
              </svg><span> &nbsp; 500+</span>
            </a>
        </div>
        <div class="in icon">
            <a href="">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="30" height="30" >
                <path fill="#000000" d="M14.5 0h-13c-0.825 0-1.5 0.675-1.5 1.5v13c0 0.825 0.675 1.5 1.5 1.5h13c0.825 0 1.5-0.675 1.5-1.5v-13c0-0.825-0.675-1.5-1.5-1.5zM11 2.5c0-0.275 0.225-0.5 0.5-0.5h2c0.275 0 0.5 0.225 0.5 0.5v2c0 0.275-0.225 0.5-0.5 0.5h-2c-0.275 0-0.5-0.225-0.5-0.5v-2zM8 5c1.656 0 3 1.344 3 3s-1.344 3-3 3c-1.656 0-3-1.344-3-3s1.344-3 3-3zM14 13.5v0c0 0.275-0.225 0.5-0.5 0.5h-11c-0.275 0-0.5-0.225-0.5-0.5v0-6.5h1.1c-0.066 0.322-0.1 0.656-0.1 1 0 2.762 2.237 5 5 5s5-2.238 5-5c0-0.344-0.034-0.678-0.1-1h1.1v6.5z"></path>
              </svg><span> &nbsp; 200+</span>
            </a>
        </div>
        <div class="gm icon">
            <a href="">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="30" height="30">
                <path d="M5.091 7.147v1.747h2.888c-0.116 0.75-0.872 2.197-2.888 2.197-1.737 0-3.156-1.441-3.156-3.216s1.419-3.216 3.156-3.216c0.991 0 1.65 0.422 2.028 0.784l1.381-1.331c-0.888-0.828-2.037-1.331-3.409-1.331-2.816 0.003-5.091 2.278-5.091 5.094s2.275 5.091 5.091 5.091c2.937 0 4.888-2.066 4.888-4.975 0-0.334-0.037-0.591-0.081-0.844h-4.806z"></path>
                <path fill="#000000" d="M16 7h-1.5v-1.5h-1.5v1.5h-1.5v1.5h1.5v1.5h1.5v-1.5h1.5z"></path>
              </svg><span> &nbsp; 100+</span>
            </a>
        </div>
      </div>
      <div class="col s12 m6 l6 foot">
      <h5 class="text-orange">Subscribe To Our Newsletter</h5>
       <form action="">
          <div class="input-field">
            <label for="news" data-error="wrong" data-success="right">Please enter your email Address</label>
            <input type="email" class="validate">
            <input type="submit" class="submit">
        </div>
       </form>
      </div>
    </div>
  </div>
  <script type="text/javascript" src="{% static 'js/functions.js' %}"></script>
</body>
</html>

templates/blog_detail.html
{% extends 'base.html'%}
{% load static %}
{% block extra_css %}
  <link rel="stylesheet" type="text/css" href="{% static  'fonts/font-awesome-4.4.0/css/font-awesome.min.css' %}">
{% endblock %}
{% block content %}
  <div class="banner parallax-container">
      <h1>Blogs Detail</h1>
      <div class="parallax">
          <img class="" src="{% static 'images/wallpaper.jpg' %}" alt="">
      </div>
  </div>
  <div class="container">
        <div class="row">
          <div class="col s12 m12 l12 blog-content">
            <div class="blog-header">
              <div class="blog-date">
                <h3>{{ instance.timestamp|date:"jS"}}</h3>
                <h3>{{ instance.timestamp|date:"F"}}</h3>
                <h3>{{ instance.timestamp|date:"Y"}}</h3>
              </div>
              <div class="blog-img">
                <img src="{{ instance.image.url }}" alt="">
              </div>
            </div>
            <div class="blog-main">
                <h5>{{ instance.title }}</h5>
                <p>{{ instance.content }}</p>
            </div>
            <div class="divider"></div>
            <div class="blog-info" data-path="{{ path }}">
              <span class="like"><span class="count">{{ instance.like_set.count }}</span> like{{ instance.like_set.count| pluralize }} </span>
              <span> {{ instance.comment_set.count }} comment{{ instance.comment_set.count| pluralize }} </span>
              <span> share &nbsp;<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
                              <i class="fa fa-facebook-square"></i>
                           </a>
					                 <a href="https://twitter.com/home?status={{instance.content|urlencode}} {{ request.build_absolute_uri }}">
                              <i class="fa fa-twitter-square"></i>
                           </a>
					                 <a href="https://www.linkedin.com/shareArticle?mini=true&{{ request.build_absolute_uri }}&title={{instance.title}}&summary={{instance.content|urlencode}}&source={{ request.build_absolute_uri }}">
                             <i class="fa fa-linkedin-square"></i>
                           </a>
					                 <a href="https://plus.google.com/share?url={{ request.build_absolute_uri }}">
                              <i class="fa fa-google-plus-square"></i>
                           </a>
              </span>
            <div class="divider"></div>
            <div class="blog-extra">
              {% if instance.comment_set.count is 0 %}
                <h3 style="color: silver; text-align: center" >No comments yet</h3>
              {% endif %}
              {% for comment in instance.comment_set.all %}
              <div class="comment-box">
                  <div class="commenter-info">
                    <div class="commenter-img">
                      <img src="{% static 'images/flower1.jpg' %}" alt="">
                    </div>
                    <span>{{ comment.user.username}}</span>
                    <span class="time">{{ comment.time|timesince }} ago</span>
                  </div>
                  <div class="divider"></div>
                  <div class="commenter-main">
                    <p>
                      {{ comment.content }}
                    </p>
                  </div>
              </div>
              {% endfor %}
              <div class="comment-in">
                <div class="divider"></div>
                <h4>Comment</h4>
                <p>Login to continue</p>
                <div class="face"><p>Facebook</p></div>
                <div class="goog"><p>Google+</p></div>
                <div class="divider"></div>
                <form class="" action="" method="post" style="margin-bottom: 100px">{% csrf_token %}
                  <div class="textbox" style="margin: 10px auto 0 auto;">
                    <textarea cols="30"  id="id_content" name="content" rows="10"></textarea>
                  </div>
                  <input id="id_blog" name="blog" value="{{ instance }}" type="hidden">
                  <div class="submit" style="display: block; margin-left: -3.5%;">
                    <input type="submit" value="Post">
                  </div>
                </form>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}
{% block extra-js %}
  <script type="text/javascript">
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
           var cookie = jQuery.trim(cookies[i]);
      if (cookie.substring(0, name.length + 1) == (name + '=')) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
         }
        }
      }
     return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    $(".like").click(function(){
      $.ajax({
       url : $(".big-info").attr("data-path"),
       type: 'post',
       data : { csrfmiddlewaretoken : csrftoken,
               'blog-id' : {{ instance.id }},
           },
       success : function(data) {
         console.log(data['count'])
         $(".count").text(data['count'])
       },
     });
    });
  </script>
{% endblock %}

templates/messages.html
{% for obj in chat %}
  {% if obj.sender == request.user %}
    <li class="right-msg">{{ obj.message }}</li>
    {% else%}
    <li class="left-msg"><div class="sender" data-pk={{obj.sender.id}}>{{ obj.sender}}</div>{{ obj.message }}</li>
  {% endif %}
{% endfor %}